### PR TITLE
Reorganizing distribution models

### PR DESCRIPTION
**Pull request by akshay-raj-dhamija**
This pull request makes the changes proposed in [PR#16](https://github.com/Vastlab/vast/pull/16) by @tboult. In order to keep the behaviour of the default libmr library most of the functionality in `weibull.py` was moved to `libmrTorch.py` but all the pre-existing functionality is still available in the weibull class through inheritance.

### CODE REVIEW

**Comment by akshay-raj-dhamija** [comment]
The previous [PR#41](https://github.com/Vastlab/vast/pull/41) had to be closed because the changed files were being shown more than they actually were. This was because of a rebase I performed. Please review this PR, the file https://github.com/Vastlab/vast/blob/reorganizing_distribution_models/vast/DistributionModels/weibull.py contains all changes by @tboult and these changes can be verified in https://github.com/Vastlab/vast/blob/reorganizing_distribution_models/vast/DistributionModels/Example.ipynb

**Comment by scruz13** [comment]
@tboult , we have a couple questions regarding the implementation of `FitHighFlipped`,`FitLowReversed`, and `prob` found in https://github.com/Vastlab/vast/blob/reorganizing_distribution_models/vast/DistributionModels/weibull.py .

1. In the `FitHighFlipped` function, it appears as if the only change prior to fitting is doing some sort of normalization to the data and then calling`FitLow` rather than `FitHigh`. Would it be better if we changed the naming of this function to something like `FitLowNormalized` or `FitLowFlipped`? It seems to us (@RRabinow) that `FitHigh` is never called. Now, something to consider is FitLow always returns wscore, which would be probability of knowness. Is this what is desired?

2. In the function `FitLowReversed`, we are now getting the probability of unknowness because the only change is returning `1-wscore`. Do we feel like we need a separate function for this? In https://github.com/Vastlab/vast/blob/reorganizing_distribution_models/vast/opensetAlgos/openmax.py, this behavior is handled within the OpenMax file itself rather than within https://github.com/Vastlab/vast/blob/reorganizing_distribution_models/vast/DistributionModels/weibull.py. If we prefer a separate function, then should we not also have a `FitHighReversed`? 

3. In the function `prob`, the return is no longer just the `wscore`, which we normally refer to as the probability. What is the purpose behind taking the log_probability of the Weibull and then taking its exponent? I guess this is more of a theory based question rather than coding.

**Comment by scruz13** [comment]
@akshay-raj-dhamija and @tboult , 

@RRabinow and I made some changes within the branch. Based on our discussions that `FitHighReversed` was simply changing the return of `wscore`, we decided to remove this functionality from `https://github.com/Vastlab/vast/blob/reorganizing_distribution_models/vast/DistributionModels/weibull.py` and added an argument `isReversed` to the `FitHigh` and FitLow` functions inside https://github.com/Vastlab/vast/blob/reorganizing_distribution_models/vast/DistributionModels/libmrTorch.py. We addressed the addition of this arg within https://github.com/Vastlab/vast/blob/reorganizing_distribution_models/vast/opensetAlgos/EVM.py, https://github.com/Vastlab/vast/blob/reorganizing_distribution_models/vast/opensetAlgos/openmax.py, and https://github.com/Vastlab/vast/blob/reorganizing_distribution_models/vast/opensetAlgos/multimodal_openmax.py. 

We have tested the addition of the arg in https://github.com/Vastlab/vast/blob/reorganizing_distribution_models/vast/DistributionModels/Example.ipynb. Also, we changed the training/testing data to be "Weibull-like".

Check this out and let us know what you think.

**Comment by scruz13** [comment]
@akshay-raj-dhamija, made commit and changed `isReserved` to be in https://github.com/Vastlab/vast/blob/e6f35822d6229a563b05f001057870756965c776/vast/DistributionModels/libmrTorch.py#L78 .

Appropriate function calls have been changed to address the change ( [OpenMax](https://github.com/Vastlab/vast/blob/reorganizing_distribution_models/vast/opensetAlgos/openmax.py) and [MultiModal](https://github.com/Vastlab/vast/blob/reorganizing_distribution_models/vast/opensetAlgos/multimodal_openmax.py) ).

**Comment by RRabinow** [comment]
Added warning message to pdf function as discussed with @akshay-raj-dhamija and @scruz13

**Review by RRabinow — APPROVED** [review]
All changes reviewed, tested at various stages

**Pull request merged**
